# Generated by Django 4.0.4 on 2022-10-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_like_tweet_rename_title_note_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
