# Generated by Django 4.0.4 on 2022-10-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_follow_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.IntegerField(null=True),
        ),
    ]
